language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == linux ]; then
    sudo apt-get update -qq;
    sudo apt-get install -y --no-install-recommends xorg-dev libglu1-mesa-dev;
    sudo apt-get install -y --no-install-recommends libxrandr-dev libxi-dev libxxf86vm-dev libxinerama-dev libxcursor-dev lcov;
    sudo apt-get install -y --no-install-recommends libopenal-dev libvorbis-dev libflac-dev libglfw3;
    fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
